extra_javascript:
  https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css
  https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js
  https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js
